cv:
  type: dict
  required: true
  schema:
    sections:
      type: list
      schema:
        type: dict
        schema:
          heading:
            type: string
            required: true
          contents:
            type: list
            schema:
              type: dict   # arbitrary key-value pairs allowed
