About Me:
  name: str
  email: str
  summary: str

Education:
  degree: str
  institution: str
  year: str

Experience:
  role: str
  company: str
  duration: str
  description:
    summary: str
    details: list

Projects:
  title: str
  description: str
  technologies: list

Skills:
  languages: str
  tools: str
