type: object
properties:
  name:
    type: string
  contact:
    type: object
    properties:
      email:
        type: string
        format: email
      phone:
        type: string
      linkedin:
        type: string
  experience:
    type: array
    items:
      type: object
      properties:
        company:
          type: string
        title:
          type: string
        start_date:
          type: string
        end_date:
          type: string
        description:
          type: string
required:
  - name
  - contact